catalog/urls.py
import os

from django.urls import path

from . import views


app_name = 'catalog'
urlpatterns = [
    path('books/', views.books, name="books"),
    path('authors', views.authors, name="authors"),
    path('publishers', views.publishers, name="publishers"),
    path('stores', views.stores, name="stores"),
    path('', views.index, name="index"),

    path('author/<int:book_id>/', views.author_detail, name='author_detail'),

    path('books/<int:book_id>/', views.book_detail, name='book_detail'),

    path('publisher/<int:book_id>/', views.publisher_detail, name='publisher-detail'),

path('store/<int:book_id>/', views.store_detail, name='store-detail'),
]

core/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('catalog/', include('catalog.urls')),

    ]

if settings.DEBUG:
    urlpatterns += [
        path('__debug__/', include('debug_toolbar.urls')),
    ]

catalog/models.py
from django.db import models


class Author(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pubdate = models.DateField()

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(max_length=300)
    books = models.ManyToManyField(Book)

    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render
from django.db import models
from django.db.models import Count, Avg

# Create your views here.
from .models import Author, Book, Publisher, Store



def index(request):

    num_authors = Author.objects.all().count()
    num_books = Book.objects.all().count()
    num_publishers = Publisher.objects.all().count()
    num_stores = Store.objects.all().count()

    rating_middle = Book.objects.aggregate(rating_middle=Avg('rating', output_field=models.FloatField()))
    middle_number = round(rating_middle['rating_middle'],2)
    return render(request, 'index.html', {"num_authors": num_authors, "num_books": num_books,
                                          "num_publishers": num_publishers, "num_stores": num_stores,
                                          "rating_middle": middle_number})


def authors(request):
    data = Author.objects.all()


    return render(request, 'authors.html', {"data": data})


def books(request):
    data = Book.objects.all()

    return render(request, 'books.html', {"data": data})


def publishers(request):
    data = Publisher.objects.all()

    return render(request, 'publishers.html', {"data": data})


def stores(request):
    data = Store.objects.all()
    print("NEW ______________________")
    print(Store.objects.prefetch_related("books"))


    return render(request, 'stores.html', {"data": data})


def author_detail(request, book_id):
    book_list = []
    data = Author.objects.filter(id=book_id)
    for s in Author.objects.prefetch_related('book_set').filter(id=book_id):
        for d in s.book_set.all():
            book_list.append(d)
    select_author = Author.objects.annotate(Count("book")).get(pk=book_id)
    book_counter = select_author.book__count
    return render(request, 'author-detail.html', {"book_list": book_list, "data": data, "book_counter": book_counter})


def book_detail(request, book_id):
    data = Book.objects.filter(id=book_id)
    for s in Book.objects.prefetch_related('authors').filter(id=book_id):
        for d in s.authors.all():
            author_name = d
    return render(request, 'book_detail.html', {"author_name": author_name, "data": data})


def publisher_detail(request, book_id):
    data = Publisher.objects.filter(id=book_id)
    for i in Publisher.objects.prefetch_related("book_set").filter(id=book_id):
        for g in i.book_set.all():
            book_name = g
    return render(request, 'publisher-detail.html', {"book_name": book_name, "data": data})


def store_detail(request, book_id):
    book_list = []
    data = Store.objects.filter(id=book_id)
    for s in Store.objects.prefetch_related('books').filter(id=book_id):
        for d in s.books.all():
            book_list.append(d)
    return render(request, 'store-detail.html', {"book_list": book_list, "data": data})

catalog/templates/author-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AUTHOR PROFILE</title>
</head>
<body>
    <h6>
        <a href="{% url 'catalog:index' %}" >HOME PAGE</a>
        <a href="{% url 'catalog:authors' %}" >AUTHORS</a>
        <a href="{% url 'catalog:books' %}" >BOOKS</a>
        <a href="{% url 'catalog:publishers' %}" >PUBLISHERS</a>
        <a href="{% url 'catalog:stores' %}" >STORES</a>
    </h6>
    <hr>
    <strong>  AUTHOR PROFILE</strong>
    <hr>
    {% for list in data %}
        <h3> {{list.name}} </h3>
        <h4> this author have {{book_counter}} books</h4>
        <em>  {{list.age}} years old</em>
    {% endfor %}
    <hr>
    <strong> BOOK LIST </strong>
    <hr>
    {% for list in book_list %}
        <h4> {{list.name}} </h4>
    {% endfor %}
</body>
</html>

catalog/templates/authors.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Authors</title>
</head>
<body>
    <h6><a href="{% url 'catalog:index' %}">HOME PAGE</a></h6>
    <h1> AUTHORS </h1>
    {% for list in data %}
        <hr>
        <strong> <a href="/catalog/author/{{ list.id }}/">{{list.name}} </a></strong>
    {% endfor %}
    <hr>

</body>
</html>

catalog/templates/book_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BOOK PROFILE</title>
</head>
<body>
    <h6>
        <a href="{% url 'catalog:index' %}" >HOME PAGE</a>
        <a href="{% url 'catalog:authors' %}" >AUTHORS</a>
        <a href="{% url 'catalog:books' %}" >BOOKS</a>
        <a href="{% url 'catalog:publishers' %}" >PUBLISHERS</a>
        <a href="{% url 'catalog:stores' %}" >STORES</a>
    </h6>
    {% for list in data %}
        <h3> {{list.name}} </h3>
        <hr>
        <strong>  AUTHOR : {{author_name}} </strong>
        <hr>
        <h5><strong>  BOOK INFORMATION </strong></h5>

        <h6><em>PAGES:</em><strong> {{list.pages}} </strong></h6>
        <h6><em>PRICE:</em><strong> {{list.price}} </strong></h6>
        <h6><em>RATING:</em><strong> {{list.rating}} </strong></h6>
        <h6><em>PUBLISHER:</em><strong> {{list.publisher}} </strong></h6>
        <h6><em>DATE OF PUBLICATION:</em><strong> {{list.pubdate}} </strong></h6>
        <hr>
    {% endfor %}



</body>
</html>

catalog/templates/books.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Books</title>
</head>
<body>
    <h6><a href="{% url 'catalog:index' %}">HOME PAGE</a></h6>
    <h1> BOOKS </h1>
    {% for list in data %}
        <hr>
    <strong><a href="/catalog/books/{{ list.id }}/"> {{list.name}} </strong>
    {% endfor %}
    <hr>

</body>
</html>

catalog/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <H2>HOME PAGE</H2>
    <h5><a href="{% url 'catalog:authors' %}">Authors: </a>{{ num_authors }}</h5>
    <h5><a href="{% url 'catalog:books' %}">Books: </a>{{ num_books }}</h5>
    <h6> average books rating : {{ rating_middle }}</h6>
    <h5><a href="{% url 'catalog:publishers' %}">Publisher: </a>{{ num_publishers }}</h5>
    <h5><a href="{% url 'catalog:stores' %}">Stores: </a>{{ num_stores }}</h5>


</body>
</html>

catalog/templates/publisher-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PUBLISHER PROFILE</title>
</head>
<body>
   <h6>
        <a href="{% url 'catalog:index' %}" >HOME PAGE</a>
        <a href="{% url 'catalog:authors' %}" >AUTHORS</a>
        <a href="{% url 'catalog:books' %}" >BOOKS</a>
        <a href="{% url 'catalog:publishers' %}" >PUBLISHERS</a>
        <a href="{% url 'catalog:stores' %}" >STORES</a>
   </h6>
   <hr>
    <strong>  PUBLISHER PROFILE</strong>
    <hr>
    {% for list in data %}
        <h3>{{list.name}} </h3>
    {% endfor %}
    <hr>
    <strong> BOOK LIST </strong>
    <hr>
    {{ book_name }}
</body>
</html>

catalog/templates/publishers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publishers</title>
</head>
<body>
    <h6><a href="{% url 'catalog:index' %}">HOME PAGE</a></h6>
    <h1> PUBLISHERS </h1>
    {% for list in data %}
        <hr>
        <strong> <a href="/catalog/publisher/{{ list.id }}/"> {{list.name}} </a></strong>
    {% endfor %}
    <hr>

</body>
</html>

catalog/templates/store-detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>AUTHOR PROFILE</title>
</head>
<body>
    <h6>
        <a href="{% url 'catalog:index' %}" >HOME PAGE</a>
        <a href="{% url 'catalog:authors' %}" >AUTHORS</a>
        <a href="{% url 'catalog:books' %}" >BOOKS</a>
        <a href="{% url 'catalog:publishers' %}" >PUBLISHERS</a>
        <a href="{% url 'catalog:stores' %}" >STORES</a>
    </h6>
    <hr>
    <strong>  AUTHOR PROFILE</strong>
    <hr>
    {% for list in data %}
        <h3> {{list.name}} </h3>
        <em>  {{list.age}} years old</em>
    {% endfor %}
    <hr>
    <strong> BOOK LIST </strong>
    <hr>
    {% for list in book_list %}
        <h4> {{list.name}} </h4>
    {% endfor %}
</body>
</html>

catalog/templates/stores.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Stores</title>
</head>
<body>
    <h6><a href="{% url 'catalog:index' %}">HOME PAGE</a></h6>
    <h1> STORES </h1>
    {% for list in data %}
        <hr>
    <strong> <a href="/catalog/store/{{ list.id }}/"> {{list.name}} </a></strong>
        {% for list in books %}
            <p> {{list.name}}</p>
        {% endfor %}
        <p> {{list.book}}</p>
    {% endfor %}
    <hr>

</body>
</html>